# Generated by Django 5.1.1 on 2024-09-13 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_topic_hive_creator_message_hive_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hive',
            options={'ordering': ['-updated', '-created_at']},
        ),
        migrations.AddField(
            model_name='hive',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
